mysql:
  username: ""
  password: ""
  url: "example:3306/ultima"
  
experimental:
  poison: true
  # in ticks
  missile-cooldown: 8

# Blocks that cannot intersect bounding boxes of schematics
# Players also cannot right click on these blocks with items.
cancel-schematic:
  - BARRIER
  - OBSIDIAN
  - CRYING_OBSIDIAN
  - NETHER_PORTAL

# Blocks that can be collected with the Deconstructor passive
# Check is contains, so no color specifications needed
deconstructor-blocks:
  - SLIME_BLOCK
  - REDSTONE_BLOCK
  - PISTON
  - OBSERVER
  - HONEY_BLOCK
  - GLAZED_TERRACOTTA
  - CONCRETE
 
# Things cannot be placed higher than this
max-height: 256
    
# When min player requirements met for each arena, 
# how long do players wait for to start game (s)
lobby-wait-time: 30

# When lobby is full, how long do players wait for (s)
lobby-wait-time-full: 10

# How long to wait for a tie before declaring victory for a team
tie-wait-time: 5

# When victory, how long is the screen displayed before world resets
# and players kicked to main lobby.
victory-wait-time: 15

# At what point should the countdown send messages and play sounds
lobby-countdown-near: 5

### The below section is copied from default-settings.yml.   ###
### default-settings.yml will be removed in the future - all ###
### future config lookups should use this section instead    ###

# The player capacity. 10 means 5 players per team.
# Additional players can still join the arena, but they can only spectate.  
arena-cap: 20
  
# Length of game before a tie is declared, in minutes  
game-length: 30

# Frequency of giving items, based on how many players are on a team.
item-frequency:
  # ex. for 1 player on a team, give items every 10 seconds
  1: 15
  2: 20
  # 3 and above
  3: 25

# Maximum number of missiles OR utility a player can have
inventory-limit: 4

# Amount of ticks items cannot be used after respawning
respawn-disable: 10

# Give items faster as game time nears end   
chaos-mode:
  # Activates when this many minutes are left in the game
  time-left: 10
  # Multiply item-frequency by this amount
  multiplier: 2
  
# Min number of players to start countdown for a game  
minimum-players: 2

# square worldborder with width radius*2
worldborder:
  center:
    x: 0
    z: 0
  radius: 250

# Square barrier between the lobby and the map in each world
# Note: center is the absolute location in the world
# Note: the barrier runs in the Y and Z plane
barrier:
  length: 256
  center:
    x: 52
    z: 0
    
spawn:
  x: 143.5
  y: 64.5
  z: 89.5
  yaw: -90.0
  pitch: 0.0