name: MissileWars
version: 0.7.2
main: com.leomelonseeds.missilewars.MissileWarsPlugin
api-version: 1.20
authors: [ M310N, Vhbob ]
description: A MissileWars plugin for UltimaMC
commands:
  MissileWars:
    description: The core Missile Wars command
    aliases:
      - mw
      - umw
  Spectate:
    description: Spectate the MissileWarsGame
  VoteMap:
    description: Open the map voting GUI
depend:
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
  - Citizens
  - WorldGuardExtraFlags
  - DiscordSRV
  - Vault
  - Parkour
  - Essentials
  - ProtocolLib